Origin/discount.css
andrewwwmatsko/magic-coders pull request #15
Opened 2024-02-29 18:10 UTC by AlexOstashevskiy

2024-02-29 21:45 UTC, AlexOstashevskiy commented
Дякую)

On Thu, Feb 29, 2024 at 4:45 PM Andrii ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Секція складається з 1 елемента - h2
>
> Щоб виділити "discount up to 40%!" цю фразу треба огорнути в span
>
> Потім навішати стилі для спану на спан, а для всьго заголовка - на h2
>
> відповідно буде багато зайвого цсс, який треба буде видалити
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/andrewwwmatsko/magic-coders/pull/15#pullrequestreview-1909928323>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BE6ZLGMXV5NBWXGIQJCDSCDYV6QNZAVCNFSM6AAAAABEANHLROVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMBZHEZDQMZSGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-01 13:33 UTC, andrewwwmatsko commented on src/partials/discount.html
забери DOCTYPE, адже він маж бути тільки в index.html

твій файл підключений до головного хтмл, тому в секції має бути тільки тег section

2024-03-01 13:36 UTC, andrewwwmatsko commented on src/css/discount.css
> +  font-family: Arial, sans-serif;
по макеті фону фемілі має бути Inter Tight, але воно вже прописане для боді в загальних стилях, тому це можна повністю забрати

також цей клас ти ніде не використовуєш, тому видали його

2024-03-01 13:39 UTC, andrewwwmatsko requested changes
прописав стилі на класи, а класи не використовуєш

додай клас на h2 і повідай на нього ці стилі:

color: #141414;
font-size: 48px;
font-weight: 600;
line-height: 50px;
letter-spacing: -0.72px;
text-transform: uppercase;

на спан такі:

color: #FBFBFB;
font-size: 48px;
font-weight: 600;
line-height: 50px; /* 104.167% */
letter-spacing: -0.72px;
text-transform: uppercase;

також переведи letter spacing і line-height в множники

як зробиш мобільну версію - тоді кидай коміт мені, коли я прийму - тоді вже берись за планшетну версію

2024-03-01 13:51 UTC, AlexOstashevskiy commented
Привіт) До стилів ще не дійшов вчора, пізно приїхав, написав тільки HTML,
знаю що Doctype не треба…сьогодні буду ще робити)
Дякую)

On Fri, Mar 1, 2024 at 8:39 AM Andrii ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> прописав стилі на класи, а класи не використовуєш
>
> додай клас на h2 і повідай на нього ці стилі:
>
> color: #141414;
> font-size: 48px;
> font-weight: 600;
> line-height: 50px;
> letter-spacing: -0.72px;
> text-transform: uppercase;
>
> на спан такі:
>
> color: #FBFBFB;
> font-size: 48px;
> font-weight: 600;
> line-height: 50px; /* 104.167% */
> letter-spacing: -0.72px;
> text-transform: uppercase;
>
> також переведи letter spacing і line-height в множники
>
> як зробиш мобільну версію - тоді кидай коміт мені, коли я прийму - тоді
> вже берись за планшетну версію
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/andrewwwmatsko/magic-coders/pull/15#pullrequestreview-1911205676>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BE6ZLGON3NXIY76IVA7J2DLYWCAKLAVCNFSM6AAAAABEANHLROVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMYTSMJRGIYDKNRXGY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-03-03 00:02 UTC, andrewwwmatsko commented on src/partials/discount.html
> +  <h2>
додай будь ласка клас на h2

2024-03-03 00:02 UTC, andrewwwmatsko commented on src/css/discount.css
> +  .massage br {
це щось зайве, видали будь ласка

2024-03-03 00:04 UTC, andrewwwmatsko commented on src/css/discount.css
> +  display: flex;
це не потрібне, в тебе в секції один елемент, а не декілька, тому флекс нічого не робить 

видали все флекс, флекс дірекшн, джастіфай контент і елайн айтемс

2024-03-03 00:34 UTC, andrewwwmatsko commented on src/css/discount.css
> +  padding: 80px 10px 80px 10px;
горизонтальні падінги можете забрати, оскільки вони будуть йти від контейнера.

2024-03-03 00:34 UTC, andrewwwmatsko commented on src/css/discount.css
> +  text-align: center;
не потрібно для секції це

2024-03-03 00:35 UTC, andrewwwmatsko commented on src/css/discount.css
> +  width: 100%;
max-width: 335px

2024-03-03 00:35 UTC, andrewwwmatsko commented on src/css/discount.css
> +  line-height: 1.04167;
це все стилі для тексту, а не для секції - тому видаліть будь ласка

2024-03-03 00:35 UTC, andrewwwmatsko commented on src/css/discount.css
> +  text-align: left;
дефолтне значення тому можна видалити

2024-03-03 00:36 UTC, andrewwwmatsko commented on src/css/discount.css
> +  line-height: 1.04167;
заокругліть до 1.04, щоб симпатичніше виглядало

2024-03-03 00:36 UTC, andrewwwmatsko commented on src/css/discount.css
> +  display: inline-block;
це не потрібне

2024-03-03 00:37 UTC, andrewwwmatsko commented on src/css/discount.css
> +  padding: 5px 10px;
по макету інші падінги ( 3px 10px 0 10px)

2024-03-03 00:37 UTC, andrewwwmatsko commented on src/css/discount.css
> +  width: 100%;
зайве значення, можна видаляти

2024-03-03 00:37 UTC, andrewwwmatsko commented on src/css/discount.css
> +@media only screen and (min-width: 768x) {
min-width: 768px (букву р загубили)

2024-03-03 01:21 UTC, andrewwwmatsko commented on src/css/discount.css
> +  margin: auto;
марджин авто буде йти від контейнера, тому можна видаляти

2024-03-03 01:22 UTC, andrewwwmatsko commented on src/css/discount.css
> +  .massage {
два різних фонт сайзи?

2024-03-03 01:22 UTC, andrewwwmatsko commented on src/css/discount.css
> +@media only screen and (min-width: 1279px) {
1280

2024-03-03 01:23 UTC, andrewwwmatsko requested changes
залишив деякі коменти + слак

також на мітингу поясню детальніше

2024-03-03 18:43 UTC, closed without merging