Fresh html+css Order html+css
andrewwwmatsko/magic-coders pull request #16
Opened 2024-02-29 20:24 UTC by Rudiarity

2024-02-29 21:48 UTC, andrewwwmatsko commented on src/css/order.css
> +a{
скидання стилів є в styles.css, тому це зайве

2024-02-29 21:51 UTC, andrewwwmatsko commented on src/css/order.css
> +    font-family: "Studio Pro";
оскільки цей шрифт не підключений, використай поки Inter Tight - коли ментор скаже як його треба підключити (він відсутній на Google Fonts) - тоді підключимо його

2024-02-29 22:00 UTC, andrewwwmatsko commented on src/img/fresh/fresh-mob-1x.png
докачай фотографії для планшету і для десктопу (+ ретіни)

2024-02-29 22:01 UTC, andrewwwmatsko commented on src/partials/fresh-harvest.html
> +      <h1 class="title_fresh">Fresh <span class="title_words_fresh">Harvest</span> Box has got you covered</h1>
h1 в нас використовується в hero, і h1 може бути лише 1 на сторінці. тому поміняй його на h2

2024-02-29 22:03 UTC, andrewwwmatsko commented on src/css/fresh-harvest.css
на контейнер container_main додай флес, flex-direction column і align items:center - воно вирівняє форму по центру

2024-02-29 22:06 UTC, andrewwwmatsko commented on src/partials/order.html
> +    <div class="container_image">
для чого img огортати в div?

2024-02-29 22:07 UTC, andrewwwmatsko commented on src/partials/order.html
> +<div class="container_list">
не потрібний контейнер для списку. ol цілком викронує цю функцію

2024-02-29 22:10 UTC, andrewwwmatsko commented on src/partials/order.html
> +  <ol class="main_list">
елементи списку є li

прибери діви, контейнером для групи елементів списку є лішки, накладай класи на них

2024-02-29 22:12 UTC, andrewwwmatsko requested changes
залишив коменти для секцій

загальний комент: не потрібно огортати елементи в div, якщо він не виконує функцій (наприклад, ol > div> li - немає сенсу, бо має бути ol > li)

також font family прописаний в загальних стилях, тому його не потрібно ще раз прописувати

2024-03-02 13:34 UTC, andrewwwmatsko commented on src/css/fresh-harvest.css
> +  padding: 80px 20px;
padding 80px 0, адже бокові відступи йдуть від контейнера

2024-03-02 14:39 UTC, andrewwwmatsko commented on src/partials/fresh-harvest.html
> +    <div class="container_main">
цей div зайвий - просто додай клас container_main через пробіл до  загального контейнера

2024-03-02 14:44 UTC, andrewwwmatsko commented on src/partials/fresh-harvest.html
> +          <textarea type="submit" class="container_comment" name="user_comment" id="user_comment" placeholder="Comment"></textarea>
placeholder стоїть не там де має бути, перевір

2024-03-02 14:45 UTC, andrewwwmatsko commented on src/partials/fresh-harvest.html
> +            <input class="input_label" type="email" name="email" placeholder="Email" pattern="([A-z0-9_.-]{1,})@([A-z0-9_.-]{1,}).([A-z]{2,8})" required>
коли починаєш писати в input воно пише не там де треба --> додай падінги на інпут, щоб було правильно (починало писати з місця де є плейсхолдер)

2024-03-02 14:47 UTC, andrewwwmatsko commented on src/css/fresh-harvest.css
> +  margin-top: 20px;
25px

2024-03-02 14:49 UTC, andrewwwmatsko commented on src/css/fresh-harvest.css
> +.fitback_form{
лексична помилка feedback

2024-03-02 14:50 UTC, andrewwwmatsko commented on src/css/fresh-harvest.css
> +font-family: "Inter Tight";
забери всюди font-family адже воно прописане для боді, і воно наслідує

2024-03-02 14:50 UTC, andrewwwmatsko commented on src/css/fresh-harvest.css
> +font-style: normal;
це теж всюди (крім тегу address) зайве

2024-03-02 15:26 UTC, andrewwwmatsko commented on src/css/order.css
> +.image{
контейнеру фотографії давай падінг, а не самій фотографії

2024-03-02 15:27 UTC, andrewwwmatsko commented on src/css/order.css
> +font-family: "Inter Tight",sans-serif ;
видали font family, бо вона є в боді

2024-03-02 15:28 UTC, andrewwwmatsko commented on src/partials/order.html
>  <section class="order">
на секцію дай background color  - тому в тебе і при розтягуванні картинки фон стоїть на місці

2024-03-02 15:28 UTC, andrewwwmatsko requested changes
Лишив коменти в файлах

2024-03-02 15:53 UTC, closed without merging

2024-03-02 16:00 UTC, Rudiarity commented on src/css/fresh-harvest.css
> +font-style: normal;
Що саме зайве не зрозумів