footer-tab
andrewwwmatsko/magic-coders pull request #28
Opened 2024-03-02 22:31 UTC by Keeldg

2024-03-02 23:10 UTC, andrewwwmatsko commented on src/css/footer.css
> +  .footer-logo-text {
я би ще дав max-width: 265px, щоб при розтягуванні текст не літав по всьому фужеру

2024-03-02 23:14 UTC, andrewwwmatsko requested changes
залишив комент у файлі цсс. також поміняйте геп для планшету в планшеті для .footer-nav на 64px (у вас 40 тягнеться з мобілки)

також відступ між .footer-info і .footer-privacy має бути 100px

2024-03-03 18:41 UTC, Keeldg commented
виправила лого, додала гепи та десктоп

2024-03-03 19:20 UTC, andrewwwmatsko commented on src/css/footer.css
> +@media screen and (min-width: 1280px) {
.footer-info {gap:302px}

2024-03-03 19:25 UTC, andrewwwmatsko commented on src/css/footer.css
> +@media screen and (min-width: 1280px) {
.footer-logo-text {width: 265px}

2024-03-03 19:26 UTC, andrewwwmatsko requested changes
залишив

2024-03-03 19:43 UTC, Keeldg commented
додала геп 302, тепер перше посилання 2 строчки

2024-03-03 20:12 UTC, Keeldg commented
поставила флекс на футер контейнері загальному

2024-03-03 20:54 UTC, andrewwwmatsko approved these changes
Good job!

2024-03-03 20:54 UTC, merged