footer-mobile-branch
andrewwwmatsko/magic-coders pull request #9
Opened 2024-02-29 01:43 UTC by Keeldg

2024-02-29 15:00 UTC, andrewwwmatsko requested changes
я думаю, що "footer-privacy" елементи мають бути посиланнями. тобто ul > li > a

також, у вас є li з текстом (38 рядок) - будь ласка обгорніть текст в p

2024-02-29 23:27 UTC, Keeldg commented
footer-mobile-end можна дивитись

2024-03-01 13:13 UTC, andrewwwmatsko commented on src/css/footer.css
.footer {
  background-color: cadetblue;
} - треба забрати

2024-03-01 13:23 UTC, andrewwwmatsko commented on src/css/footer.css
Відступи між li в ul (how it works, vegetables, review) мають бути по 14px

2024-03-01 13:25 UTC, andrewwwmatsko commented on src/css/footer.css
Також не працюють падінги на секцію - попробуйте виправити

2024-03-01 13:26 UTC, andrewwwmatsko commented on src/partials/footer.html
.footer-privacy-p в тексті маюти ©Green Harvest 2023 (пропустили слово Green).

2024-03-01 13:26 UTC, andrewwwmatsko requested changes
Залишив коментарі до файлів

2024-03-03 14:49 UTC, closed without merging